# Generated by Django 3.2.6 on 2022-10-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("preco", models.FloatField()),
                ("percentual_comissao", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produtos.item",
                    ),
                ),
            ],
            bases=("produtos.item",),
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="produtos.item",
                    ),
                ),
            ],
            bases=("produtos.item",),
        ),
    ]
