# Generated by Django 3.2.6 on 2022-10-22 17:20

from django.db import migrations, models
import produtos.validators.validate_comissao


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="percentual_comissao",
            field=models.IntegerField(
                validators=[produtos.validators.validate_comissao.validate_comissao]
            ),
        ),
    ]
