# Generated by Django 3.2.6 on 2022-10-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvenda",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="vendas.venda",
                verbose_name="itens",
            ),
        ),
    ]
