# Generated by Django 3.2.6 on 2022-10-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_alter_itemvenda_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvenda",
            name="prceo_item_unidade",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itensvenda",
                to="vendas.venda",
            ),
        ),
    ]
