# Generated by Django 3.2.6 on 2022-10-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_auto_20221022_1720"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemvenda",
            old_name="prceo_item_unidade",
            new_name="preco_item_unidade",
        ),
    ]
