# Generated by Django 3.2.6 on 2022-10-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_rename_prceo_item_unidade_itemvenda_preco_item_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvenda",
            name="comissao_vendedor",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="preco_item_unidade",
            field=models.FloatField(default=0),
        ),
    ]
